[#32] Comment 조회 및 업데이트 기능 구현
phdljr/trollo pull request #102
Opened 2023-12-30 15:24 UTC by pangseon

## 작업 사항
- Comment 업데이트 기능 구현
- 유저가 작성한 Comment 조회 기능 구현
## 작업 목록
- CommentService.java
- CommentRepository
- CommentDto 패키지 하위 파일들
- CommentController.java
## 수정 사항

## 관련 이슈
close #35 close #36 
`ex) close #4 #5`

2023-12-30 17:08 UTC, phdljr requested changes
고생하셨습니다!
리뷰 확인 부탁드립니다!

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +        return new ApiResponse<>(commentService.findUserComment(req));
42번 코드처럼, 상태 코드도 남겨주면 어떨까요?

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +    @PatchMapping
업데이트 HTTP 메소드에 대해선 `PUT`을 사용하는 것을 권고한다고 합니다.
`@PutMapping`을 사용하시는는건 어떨까요?

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +            throw new IllegalArgumentException("Not_Found_Entity");
커스텀 예외를 생성해서 적용해보시면 어떨까요?
ex) `throw new NotFoundCommentException(ErrorCode.NOT_FOUND_COMMENT)`

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +            req.nickname());
id만으로 조회할 수 있을 것 같아보입니다!
commentId와 nickname을 기준으로 entity를 조회하는 이유가 있을까요?

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +    public ApiResponse<List<CommentGetResUser>> getComments(@RequestBody CommentGetReqUser req) {
사용자의 유저 데이터를 받아서, 작성자만 수정할 수 있는 검증 로직을 추가해보시면 어떨까요?(서비스단에서)

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +    public CommentUpdateRes updateComment(CommentUpdateReq req) {
댓글 수정은 작성자만 수정할 수 있도록 검증하는 로직이 있어야 할 것 같습니다!

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
>  package org.nbc.account.trollo.domain.comment;
Service 클래스는 우리가 인터페이스와 구현체를 분리하기로 정했습니다!
코드 컨밴션을 지켜주시면 좋을 것 같습니다!

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
> +@Builder
`@Builder`는 생성자에 붙이는게 어떨까요?

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentRepository.java
Repository는 `repository` 패키지를 따로 생성해서 관리해두는 것이 어떨까요?

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
>  public class CommentEntity extends BaseEntity {
클래스명에 Entity를 삭제하는 것이 좋을 것 같습니다!

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetResUser.java
> +public record CommentGetResUser(
클래스 네이밍을 일관성있게 작성해주신다면 좋을 것 같습니다!

2023-12-30 17:08 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentGetReqUser.java
> +public record CommentGetReqUser(
DTO 이름은 Req나 Res로 끝내는게 더욱 일관성있을 것 같습니다!

클래스 이름 끝에 User를 붙이신 이유가 따로 있을까요?

2023-12-30 17:19 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
> +@Builder
그래서 현재 지금 업데이트를 하기 위해서는 id 값을 불러와서 작업을 진행해야하는데 이렇게 되면 처음 생성자를 사용한 이유가 Id값에 Builder를 사용할 필요가 없다고 판단되었기 때문에 따로 생성자를 만들어두었습니다. 그래서 제 생각에는 차라리 생성자를 없애는게 더 좋다고 생각되고 있는데 어떤 방식이 좋을까요 리뷰 달아주시면 확인 후 반영해보도록 하겠습니다

2023-12-30 17:20 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +        return new ApiResponse<>(commentService.findUserComment(req));
변경하도록 하겠습니다

2023-12-30 17:20 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +    @PatchMapping
변경하도록 하겠습니다

2023-12-30 17:22 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
>  public class CommentEntity extends BaseEntity {
네 알겠습니다

2023-12-30 17:24 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetResUser.java
> +public record CommentGetResUser(
이 부분은 현재 카드에 달린 전체 Comment와 User가 작성한 Comment의 내용을 분리하기 위해서 이렇게 작성을 하였는데 차라리 **CommetGetUserRes** 라는 형태로 변경을 하는게 좋을까요?

2023-12-30 17:24 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentGetReqUser.java
> +public record CommentGetReqUser(
위에와 같은 이유입니다

2023-12-30 17:51 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetResUser.java
> +public record CommentGetResUser(
아 그런 이유가 있었군요!
저는 후자가 더 나을 것 같습니다 ㅎㅎ

2023-12-30 17:51 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
> +@Builder
아 엔티티의 변경 내용에 대해서 따로 setter를 만들지 않고, save를 사용해서 변경 내용을 반영시키는 방식이군요.
그러면 id가 필요할테니, 클래스단에 붙이는게 더 나을 것 같습니다!

2023-12-30 17:53 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +            req.nickname());
update를 하기 위해서는 댓글을 작성한 사용자와 수정하려고 하는 댓글의 Id 값이 일치해야지만 수정할 수 있게 하기 위해서 이렇게 작성하였습니다

2023-12-30 17:53 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetResUser.java
> +public record CommentGetResUser(
고렇다면 후자로 다 변경하겠습니다~

2023-12-30 17:54 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
> +@Builder
네 그러면 클래스단에만 붙여서 사용하도록 하겠습니다 의견 감사합니다~

2023-12-30 17:57 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +    public ApiResponse<List<CommentGetResUser>> getComments(@RequestBody CommentGetReqUser req) {
그러면 조회든 수정이든 삭제든 다 동일하게 유저에 대한 정보를 토큰에서 가져와서 비교하는 로직을 작성하면 괜찮을것 같은데 위와 같은 방법으로 진행해봐도 괜찮을까요? 아니면 다른 뭐 추천해주실만한 방법이 있으실까요?

2023-12-30 18:03 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +            req.nickname());
아! 이해했습니다.

그러나, nickname같은 경우는 변하는 값이고, unique값이 아니라서 의도치않은 값이 조회될 수도 있을 것 같아요.

그렇다면 id로 조회한 다음, comment의 user(작성자)를 가져와서 사용자(요청자)의 user와 비교하는 로직을 추가하면 어떨까요?
ex) 
```
Comment comment = commentRepository.findById(req.commentId());
if(comment.getUser().getId().equals(컨트롤러로부터 받아온 요청자의 ID) // @AuthenticationPrinciple
```

2023-12-30 18:06 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
> +    public ApiResponse<List<CommentGetResUser>> getComments(@RequestBody CommentGetReqUser req) {
`유저에 대한 정보를 토큰에서 가져와서 비교하는 로직`
저는 이 방식을 추천드립니다!

실제로 구현하실때는, 사용자가 해당 댓글이 속한 보드에 있는지를 검증하는 로직이 필요할 것 같습니다!

2023-12-31 08:27 UTC, phdljr commented
테스트

2023-12-31 19:42 UTC, phdljr requested changes
고생하셨습니다!
리뷰 확인 부탁드리며, push를 하시기 전에 develop의 내용을 merge해주시길 바랍니다!
+ 코드 포맷팅

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        Long board = findBoard(cardId);
메소드 명과 필드를 boardId로 바꾸는건 어떨까요?
Board 객체를 반환시키는걸로 오해할 수도 있을 것 같습니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        UserBoard userBoard = findUserBoard(board, userId);
Optional을 사용해서 예외처리를 해보는건 어떨까요?
그러면 따로 메소드를 만들어주지 않아도 될 것 같아요!
게다가, 예외 처리를 해주는 if문도 따로 만들어주지 않아도 된답니다! (42-44 코드)

ex) `UserBoard userBoard = userBoard.findByUserIdAndBoardId(userId, boardId).orElseThrow(()->new NotFoundUserBoardException(ErrorCode.NOT_FOUND_USER_BOARD));`

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +    public Long findBoard(Long cardId) {
해당 메소드가 외부에서도 쓰인다면 public으로 해두는 것이 맞지만,
CommentService에서만 쓰이는 메소드라면 private로 접근 제어자를 수정하는게 더 나을 것 같습니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        Card card = cardRepository.findById(cardId).orElseThrow();
orElseThrow에는 어떤 예외를 던져주는 것인가요?
내용이 비어있는 듯 합니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
>          }
이 부분도, Optional을 사용해서 예외처리를 해보시면 어떨까 싶네요!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        return null;
`return`이 여러 개 있으면 나중에 유지보수할 때 많이 골치아플 수 있답니다..!
코드 앞단에서 검증을 거치고, 마지막에 실행시킴으로써 `하나의 return만 존재`하도록 리팩토링을 진행시키면 어떨까요?

검증 부분도 Optional을 사용한다면 좀 더 가독성 좋게 코드를 고칠 수 있을 것 같습니다.

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
>      }
해당 메소드가 외부에서도 쓰인다면 public으로 해두는 것이 맞지만,
CommentService에서만 쓰이는 메소드라면 private로 접근 제어자를 수정하는게 더 나을 것 같습니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/controller/CommentController.java
> +@RequestMapping("api/v1")
`api` 앞에 `/` 가 빠진 것 같군요!
`/api/v1`으로 수정해주시면 좋을 것 같습니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/controller/CommentController.java
> +    @PostMapping("/{cardId}/comments")
RESTful한 API를 작성하기 위해, `/api/v1/cards/{cardId}/comments`로 작명하시는 건 어떨까요?

예를 들어, `/api/v1/1/comments`라고 요청을 보낸다면, 1이 어떤 의미를 뜻하는지 이해하기가 어려울 수도 있을 듯 합니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/controller/CommentController.java
> +        System.out.println("cardId = " + cardId);
테스트용으로 작성하신 코드인 것 같은데,
push하실 때는 삭제해주시길 바랍니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/controller/CommentController.java
> +    @DeleteMapping("/{cardId}/comments")
RESTful한 API를 작성하기 위해, /api/v1/cards/{cardId}/comments로 작명하시는 건 어떨까요?

예를 들어, /api/v1/1/comments라고 요청을 보낸다면, 1이 어떤 의미를 뜻하는지 이해하기가 어려울 수도 있을 듯 합니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/entity/Comment.java
> +@Builder
Lombok 어노테이션은 맨 위에 달아주시면 좋을 것 같습니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/mapper/CommentServiceMapper.java
> +    }
이런 경우는 해당 메소드가 필요없을 듯 합니다.
사용될 메소드에 `@Mapping(source = "user.nickname", target = "nickname")`만 달아주면 알아서 매핑이 될겁니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/comment/repository/CommentRepository.java
> +    List<Comment> findByUserNickname(String nickname);
`findByXXX`를 사용할 것인지, `findCommentByXXX`를 사용할 것인지 메소드 명을 통일시켜줄 필요가 있을 듯 합니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/repository/UserRepository.java
> +    User findUserById(Long id);
findByXXX를 사용할 것인지, findCommentByXXX를 사용할 것인지 메소드 명을 통일시켜줄 필요가 있을 듯 합니다!

2023-12-31 19:42 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
> +    FORBIDDEN_ACCESS_CARD(HttpStatus.FORBIDDEN, "뭐지..."),
이미 develop에는 해당 내용이 추가되어 있습니다.
push를 하시기 전에, develop 내용을 merge 하셨나요?

2023-12-31 20:10 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
> +    FORBIDDEN_ACCESS_CARD(HttpStatus.FORBIDDEN, "뭐지..."),
방금 푸시할때는 머지하지 않았습니다 다시 한 번 확인 해보도록 하겠습니다

2024-01-01 14:53 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
>      }
findUserComment 메서드는 컨트롤러에서 사용되는 메서드이기 때문에 public으로 사용되어야합니다.

위 메서드는 유저가 작성한 댓글을 보여주기 위한 기능입니다~!!

2024-01-01 14:56 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        return null;
우선 적용시킨후에 다시 받아서 리팩토링 하도록 하겠습니다

2024-01-01 14:57 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
>          }
이 부분도 추후에 다시 코드 리팩토링을 할 때 하도록 하겠습니다

2024-01-01 15:00 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +        Card card = cardRepository.findById(cardId).orElseThrow();
수정하였습니다

2024-01-01 15:01 UTC, pangseon commented on src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
> +    public Long findBoard(Long cardId) {
수정하였습니다~!

2024-01-01 15:32 UTC, phdljr approved these changes

2024-01-01 15:34 UTC, closed without merging