Feat/notification get
phdljr/trollo pull request #106
Opened 2023-12-31 07:27 UTC by undiputed91

## 작업 사항
알림 조회
## 작업 목록

## 수정 사항

## 관련 이슈
close #96 
`ex) close #4 #5`

2023-12-31 08:16 UTC, phdljr requested changes
고생하셨습니다!
리뷰 확인 부탁드리겠습니다!

2023-12-31 08:16 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
Card에 양방향으로 참조가 가능한가요?
ERD상에선 Card와 Notification이 연결된 모습을 찾기가 힘드네요.

아마도 양방향으로 한다면, Board나 User에 해두는게 좋지 않을까라는 생각이 듭니다!

2023-12-31 08:16 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/entity/NotificationEnum.java
> +public enum NotificationEnum {
`NotificationEnum`보다는, `NotificationType`이 어떨까요?
사소한 것일수도 있는데, 예약어를 붙이기보단 이해도를 높일 수 있는 키워드를 적어두는게 좋은 네이밍이라고 생각합니다!

2023-12-31 08:16 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
> +        List<Notification> notificationList = notificationRepository.findAll();
사용자가 속한 보드에 관한 알림을 가져오면 어떨까 싶습니다!
특정 사용자가 속하지 않은 보드에 대한 알림을 조회할 필요는 없다고 생각됩니다!

2023-12-31 08:26 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
아 또 ERD를 무시한채 작성했었네요 대대적으로 고쳐야 할 것 같습니다.

2023-12-31 08:28 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/entity/NotificationEnum.java
> +public enum NotificationEnum {
알림 저장할때 댓글로 
"이제와서 s.a상의 erd를 확인해보니 notificationEnum또는 notificationType은 fieldName 으로 되어있고 message는 fieldContent로 되어있네요 그냥 이런게 fieldName, fieldContent로 필드명을 변경해보겠습니다."
라고 하고 변경했었는데 merge가 안된 상태에서 작성하다보니 여기는 수정 하는 것을 빼먹었습니다. 위에처럼 바꿔도 될까요?

2023-12-31 08:31 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
> +        List<Notification> notificationList = notificationRepository.findAll();
위에 대대적으로 고치면서 함께 고치겠습니다. 
별개로 체크리스트의 경우 create/update/delete가 아직 merge가 안되어서 delete의 변경이 create/update를 포함하고 있고 지금 notification-get도 notification-save의 코드를 포함하고 있는데 이전 껀 무시하고 그냥 checklist-delete와 notification-get만 수정해도 될까요?

2023-12-31 08:39 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
현재 저장메시지(fieldContent)가 예를 들어 1번 카드가 생성 되면 
`event.card().getId() + "번 카드" + event.notificationEnum().getWord() + "되었습니다.";`로
1번 카드가 생성되었습니다. 의 형태로 저장되게 해놨는데 erd상으로는 cardId는 따로 저장하지는 않고 어떤식으로 접근해야 할까요?

2023-12-31 08:43 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/entity/NotificationEnum.java
> +public enum NotificationEnum {
아예 enum명을 바꾸는게 어떤가 였군요

2023-12-31 08:58 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
다대다 관계기에 중간 테이블을 만들어 보는건 처음인지라 UserBoard를 참고할 것 같은데 UserBoardId Class는 역할이 뭔가요?

2023-12-31 09:07 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
> 다대다 관계기에 중간 테이블을 만들어 보는건 처음인지라 UserBoard를 참고할 것 같은데 UserBoardId Class는 역할이 뭔가요?

복합키를 설정해주는 클래스입니다!

2023-12-31 09:13 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
> 현재 저장메시지(fieldContent)가 예를 들어 1번 카드가 생성 되면 `event.card().getId() + "번 카드" + event.notificationEnum().getWord() + "되었습니다.";`로 1번 카드가 생성되었습니다. 의 형태로 저장되게 해놨는데 erd상으로는 cardId는 따로 저장하지는 않고 어떤식으로 접근해야 할까요?

card_id는 따로 저장해둘 필요는 없을 것 같습니다!
내용은 `TB_NOTIFICATION`의 `수정 사항`이나 `수정 내용`에 적으면 될 것 같아요!

근데, 수정 사항과 수정 내용은 뭐가 들어가야될지 저도 잘 모르겠네요..
수정 사항을 `종류`로 바꾸고, 승호님께서 작성하신 enum을 넣으면 어떨까라는 생각이 드는데 어떠신가요?

2023-12-31 09:15 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/entity/NotificationEnum.java
> +public enum NotificationEnum {
> 알림 저장할때 댓글로 "이제와서 s.a상의 erd를 확인해보니 notificationEnum또는 notificationType은 fieldName 으로 되어있고 message는 fieldContent로 되어있네요 그냥 이런게 fieldName, fieldContent로 필드명을 변경해보겠습니다." 라고 하고 변경했었는데 merge가 안된 상태에서 작성하다보니 여기는 수정 하는 것을 빼먹었습니다. 위에처럼 바꿔도 될까요?

해당 내용을 여기 PR에다가 push해두시면 반영이 될겁니다!

2023-12-31 09:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
> +        List<Notification> notificationList = notificationRepository.findAll();
> 위에 대대적으로 고치면서 함께 고치겠습니다. 별개로 체크리스트의 경우 create/update/delete가 아직 merge가 안되어서 delete의 변경이 create/update를 포함하고 있고 지금 notification-get도 notification-save의 코드를 포함하고 있는데 이전 껀 무시하고 그냥 checklist-delete와 notification-get만 수정해도 될까요?

포함하신 상태로 진행하시면 됩니다!
이전에 작성된 PR이 merge되면, 자동으로 반영이 될겁니다!
(같은 commit을 포함하고 있다면, github가 알아서 반영해주는 것 같습니다.)

2023-12-31 10:28 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
> +
"fieldName":"CREATED"(수정사항)
"fieldContent":"1번 카드가 생성되었습니다."(수정내용)로 생각했었는데 
수정사항이란 표현대신 종류로 변경은 맞는것 같고 수정내용은 일단 위와 같이 n번 카드가 ~되었습니다 메시지를 저장하는 형태로 하겠습니다.

2023-12-31 14:52 UTC, undiputed91 commented
이거 괜히 중간에 최근 develop을 pull 했더니 코드 리뷰하기 너무 힘들게 만들어 버렸네요

주요 수정 사항을 정리해 보자면 
1. erd상의 column들과 일치 시키기위해 cardEvent필드들과 notification 엔티티를 수정, 중간테이블 UserNotification을 추가했습니다.
(fieldContent는 "n번 BOARD에서 카드가 생성되었습니다." 형태로 구현했습니다.)
2. enum을 notificationType으로 변경했습니다.
3. 특정id의 board알림만 가져오게 했습니다. 참여자인지 확인하는 로직 또한 가져옴
4. 알림 처음 저장할때 usernotification에 unread상태로 저장되게 했습니다. 조회하고 read상태로 변경되게 했습니다.

정리하다보니 찾은 문제점 
userNotification의 user부분이 문제가 있는 것 같습니다. 카드 생성 당사자가 (erd상의 수정자) 알림에 저장되는데 UserNotification의 User도  사용자가 아니라 카드 생성 당사자가 저장되는 로직인듯 한데 사용자를 어떻게 접근할지 감이 좀 안옵니다. 이벤트를 사용안하는 식으로도 고려해야 할지도 모르겠네요 
지금 또 정리하다보니 떠오른게 listener를 두개 사용해야 할 듯 하네요

2024-01-01 00:33 UTC, undiputed91 commented
로그인하는 시점에 새로운 userNotification 저장 이벤트를 새로 발행해야하나 싶네요?

2024-01-01 04:42 UTC, phdljr commented
> 이거 괜히 중간에 최근 develop을 pull 했더니 코드 리뷰하기 너무 힘들게 만들어 버렸네요
> 
> 주요 수정 사항을 정리해 보자면
> 
> 1. erd상의 column들과 일치 시키기위해 cardEvent필드들과 notification 엔티티를 수정, 중간테이블 UserNotification을 추가했습니다.
>    (fieldContent는 "n번 BOARD에서 카드가 생성되었습니다." 형태로 구현했습니다.)
> 2. enum을 notificationType으로 변경했습니다.
> 3. 특정id의 board알림만 가져오게 했습니다. 참여자인지 확인하는 로직 또한 가져옴
> 4. 알림 처음 저장할때 usernotification에 unread상태로 저장되게 했습니다. 조회하고 read상태로 변경되게 했습니다.
> 
> 정리하다보니 찾은 문제점 userNotification의 user부분이 문제가 있는 것 같습니다. 카드 생성 당사자가 (erd상의 수정자) 알림에 저장되는데 UserNotification의 User도 사용자가 아니라 카드 생성 당사자가 저장되는 로직인듯 한데 사용자를 어떻게 접근할지 감이 좀 안옵니다. 이벤트를 사용안하는 식으로도 고려해야 할지도 모르겠네요 지금 또 정리하다보니 떠오른게 listener를 두개 사용해야 할 듯 하네요 그러면 userNotification은 어느시점에 저장해야 할까요?

`UserNotification`에 저장되는 `user`는 알림을 받는 사용자를 의미하는게 아닌가요?
즉, 당사자가 저장되는건 `Notification`에만 저장되고, 그 알림을 받을 사용자들을 `UserNofitication`에 저장하는 원리지 않을까 싶습니다.

2024-01-01 04:44 UTC, phdljr commented
> 로그인하는 시점에 새로운 userNotification 저장 이벤트를 새로 발행해야하나 싶네요?

이 부분에 대해선 자세한 설명을 들어보고 싶네요!
조금 더 자세한 설명을 덧붙여 주실 수 있을까요?

2024-01-01 05:38 UTC, phdljr reviewed
고생하셨습니다!
리뷰 확인 부탁드립니다!

2024-01-01 05:38 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
알림을 받을 모든 사용자(알림이 발행된 보드에 속한 사용자들)에 대한 UserNotification을 만들어서 저장해야하지 않을까 싶습니다!

2024-01-01 05:38 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
> +    public void changeNotificationStatus(UserNotification unreadStatus) {
해당 메소드는 private로 선언해도 될 것 같습니다!
그리고, 부모 메소드에 이미 Transactional이 있으니 명시적으로 @Transactional을 달아 줄 필요는 없을 것 같습니다!

2024-01-01 09:09 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
막상 다대다에 중간테이블 들어가고 하니 알림메커니즘이 너무 헷갈리네요

현재 적용되는 것은 카드를 생성할 때 이벤트에 카드 작성자, 생성된 보드, 카드상태(CREATED) 세개의 정보가 담겨서 전달됩니다. 
이벤트 리스너에서는 위의 세개의 정보를 NotificationRepository에 저장하구요

지금 구현된 상태는 위의 알림이 저장되는 동시에 이벤트리스너가 userNotification을 저장하는 형태입니다. 근데 이벤트로 정보를 받다보니 담을 수 있는 정보가 이벤트에 있던 카드 작성자였던게 문제였죠.

userNotification에 담긴 user는 카드 생성자가 아닌 알림을 받을 보드사용자 여야 하는데 당장 일단 보드 사용자를 어떤형태로 담아야 할지도 잘 파악이 안되어서 일단 보드 사용자를 저장하는 이벤트를 따로 만들어야 하나 생각했습니다. 이벤트 리스너 자체는 들어오는 파라미터의 이벤트를 통해 이벤트를 구별하는 것 같더라구요.

근데 막상 또 보드 사용자가 어느 시점에 어떤 정보로 저장이 되는지 감이 잡히지가 않아서 생각해본게 로그인하는 시점에 저장이 되어야 하나 생각을 해봤습니다.

userNotification의 상태는 read, unread, deleted로 구성되어있는데 로그인 하는 시점에 unread형태로 저장이 되었다가 조회api를 실행하면 read로 바꾸는 형태로 생각을 해본거에요

제가 뭔가 파악을 잘못하고 있는 것 같기는 해서 전반적인 흐름을 다시 체크해주시면 감사하겠습니다.

2024-01-01 09:09 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
> +    public void changeNotificationStatus(UserNotification unreadStatus) {
이거는 일단 수정해놓겠습니다.

2024-01-01 10:05 UTC, minisundev commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
저라면 findAllBy ~~ 이런 JPA Method로 알림이 발생하는 보드에 속한 User를 List로 받아온 후에 for문을 돌리든 Stream을 쓰든 해서 그 List안에 있는 모든 User에게 notification을 등록해줄 것 같습니다!

2024-01-01 10:10 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
`CardEvent`에는 `board`가 있으니, 해당 알림이 발생된 보드 id를 조회할 수 있을 겁니다.
`CardEvent`가 발생되면 `listener`에서 처리하게 될 것이고, 거기서 보드 id를 통해 `TB_USER_BOARD`에서 해당 보드 id에 속하는 모든 사용자들을 조회하면 어떨까 싶습니다!

알림을 조회하는 로직은, 따로 api를 통해 만들어두면 되지 않을까요?
조회를 하게 된 순간, 읽음 처리가 되도록 하면 어떨까 싶습니다!

일단, 승호님께서 이해하신 내용을 바탕으로 노션 S.A.의 `분석 및 시나리오`에 어떤식으로 알림에 대한 로직이 흘러가는지 간단하게 정리를 한번 해보시겠어요?

2024-01-01 10:14 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
이벤트 리스너로 발행했던 이벤트를 받아올때 함께 등록을 하면 될거 같네요 이벤트 발행시점의 보드 참여자니까
감이 좀 잡힌것 같습니다. 감사합니다. 체크리스트 쪽 해결되면 다시 요거 시도 해봐야겠네요. 그때 또 질문이 생길 수도 있어요 ㅎ
조언 감사합니다.

2024-01-01 10:29 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        userNotificationRepository.save(userNotification);
넵 조회하면 READ로 상태변경되는건 구현되어있습니다.
코드 다시 짜기 전에 시나리오 먼저 작성해볼게요

2024-01-01 15:50 UTC, phdljr approved these changes
고생하셨습니다!

2024-01-01 15:50 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
> +        }
코드가 깔끔하군요!
고생하셨습니다!

2024-01-01 23:59 UTC, merged