[#14] Feature/refactor signup and login
phdljr/trollo pull request #64
Opened 2023-12-28 13:00 UTC by minisundev

## 작업 사항
회원가입, 로그인 이슈 코드 수정

## 작업 목록
#45 annotation 순서, 공백 코드 컨벤션에 맞게 수정
#48 Exception들 CustomException으로 변경
#58 SignupReq 의 email필드 @email로 Validate
#59 login 로직 UserService로 옮기기
#60 jwt, 쿠키 유효기간 application.yml에서 불러오기
## 수정 사항

## 관련 이슈
close #45 annotation 순서, 공백 코드 컨벤션에 맞게 수정
close #48 Exception들 CustomException으로 변경
close #58 SignupReq 의 email필드 @email로 Validate
close #59 login 로직 UserService로 옮기기
close #60 jwt, 쿠키 유효기간 application.yml에서 불러오기

2023-12-28 13:17 UTC, phdljr requested changes
고생하셨습니다!! 리뷰 확인 부탁드립니다!

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/dto/request/LoginReq.java
> +
dto를 class에서 record로 바꿔볼까요?

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/dto/request/SignupReq.java
> +@Validated
컨트롤러에서 파라미터에 `@Valid`를 달아두면, dto에서는 따로 `@Validated`를 달아줄 필요는 없습니다!
ex)
```
    @PostMapping("/boards")
    public ResponseEntity<Void> createBoard(
        @Valid @RequestBody BoardCreateRequestDto boardCreateRequestDto) { ... }
```

아니면 혹시, @Validated를 달아둔 다른 이유가 있을까요?

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
>  @Setter
Entity 클래스에서 `@Setter`를 달아주는 것은 데이터의 변경성을 열어두는 것이므로, 위험한 행위일 수도 있습니다!

그러니 수정이 필요한 필드에 대해서만 따로 setter를 만들어 주는 것은 어떨까요?

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/exception/UserDomainException.java
> +public class UserDomainException extends CustomException {
코드 포멧팅 한번 해둡시다!
그러면 클래스와 메소드 사이에 빈 줄이 추가될겁니다!

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
> +      throw new UserDomainException(ErrorCode.ALREADY_EXIST_EMAIL);
커스텀 예외를 잘 적용하셨군요!
좋습니다!

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
> +@Table(name = "TB_USER")
Lombok과 분리해서 선언한 점과, Table의 이름을 컨밴션에 맞게 설정하셨군요!
매우 좋습니다 👍

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
> +    INVALID_PASSWORD_CHECK(HttpStatus.BAD_REQUEST,"password check가 password와 일치하지 않습니다."),
ErrorCode의 이름만 봐도 딱 이해가 될 정도입니다! 👍

2023-12-28 13:17 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/global/jwt/JwtUtil.java
> +  private String expiredPeriod;
아마 `Long`이나 `Integer` 형태로 바로 주입받을 수 있을 겁니다!
`String`을 `Long`이나 `Integer`으로 바꿔볼까요?

2023-12-28 13:22 UTC, minisundev commented on src/main/java/org/nbc/account/trollo/domain/user/dto/request/SignupReq.java
> +@Validated
다른 방식으로 하려다가 롤백하는거 까먹었어요!

2023-12-28 13:22 UTC, minisundev commented on src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
>  @Setter
넵

2023-12-28 13:23 UTC, minisundev commented on src/main/java/org/nbc/account/trollo/global/jwt/JwtUtil.java
> +  private String expiredPeriod;
오 그렇군요!

2023-12-28 13:26 UTC, minisundev commented on src/main/java/org/nbc/account/trollo/domain/user/dto/request/LoginReq.java
> +
넵

2023-12-29 02:02 UTC, pangseon approved these changes
늦게까지 작업하시느라 고생많으셨습니다~

2023-12-29 02:17 UTC, undiputed91 approved these changes

2023-12-29 02:46 UTC, phdljr approved these changes
고생하셨습니다!

2023-12-29 02:46 UTC, merged