[#17]Feat: checklist-create
phdljr/trollo pull request #87
Opened 2023-12-29 08:45 UTC by undiputed91

## 작업 사항
체크리스트 생성
## 작업 목록

## 수정 사항

## 관련 이슈
close #17 
`ex) close #4 #5`

2023-12-29 08:56 UTC, phdljr requested changes
고생하셨습니다!
리뷰 확인 부탁드립니다!

2023-12-29 08:56 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/checklist/entity/CheckList.java
> +@NoArgsConstructor
access를 PROTECT로 설정해두시면 더 좋습니다!

2023-12-29 08:56 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/checklist/service/impl/CheckListServiceImpl.java
> +    }
사용자가 해당 보드에 속하는지를 판단하는 코드가 필요할 것 같습니다.
초대받지 않은 사용자가 체크리스트를 생성시킬 수 없도록 만들어야 됩니다!

2023-12-29 11:00 UTC, undiputed91 commented on src/main/java/org/nbc/account/trollo/domain/checklist/service/impl/CheckListServiceImpl.java
> +    }
카드서비스에 있던 코드 참고해서 판단코드 넣었습니다.

2023-12-29 12:15 UTC, minisundev approved these changes

2023-12-30 15:00 UTC, phdljr requested changes
리뷰 확인 부탁드리겠습니다!

2023-12-30 15:00 UTC, phdljr commented on src/main/java/org/nbc/account/trollo/domain/checklist/service/impl/CheckListServiceImpl.java
> +        }
UserBoard에 추가된 사용자가 WAITING 상태인 경우도 확인해야하는 로직이 필요할 것 같습니다.
CardService에서 그런 검증 기능이 빠졌었는데, 이번에 추가했으니 한번 참고해보시길 바랍니다!

2023-12-31 09:29 UTC, phdljr approved these changes
고생하셨습니다!

2023-12-31 09:49 UTC, merged